[package]
name = "gccjit-rustexample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gccjit = { git = "https://github.com/antoyo/gccjit.rs.git", version = "1.0.0" }
